# Generated by Django 4.0.3 on 2022-04-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='User name')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='Email')),
                ('names', models.CharField(blank=True, max_length=100, null=True, verbose_name='Names')),
                ('surnames', models.CharField(blank=True, max_length=100, null=True, verbose_name='Surnames')),
                ('image', models.ImageField(blank=True, max_length=200, null=True, upload_to='profile/', verbose_name='Profile picture')),
                ('active_user', models.BooleanField(default=True)),
                ('admin_user', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
